// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'footer': string;
  'form-container': string;
  'stay-on-hover': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
