// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'closed': string;
  'container': string;
  'footer': string;
  'header': string;
  'issue': string;
  'issue-double-col': string;
  'issue-list': string;
  'issue-single-col': string;
  'issue-warning': string;
  'issueDetails': string;
  'open': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
