// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closed': string;
  'container': string;
  'issue': string;
  'issue-list': string;
  'issue-warning': string;
  'open': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
